name: GRPS39
version: "0.1"
license: "Artistic-2.0"
date: 2022-07-31
description: |
    Library of the groups of order 19683

authors:
    - name: David Burrell
      url: https://davidburrell.github.io/

maintainers:
    - name: David Burrell
      url: https://davidburrell.github.io/

GAP: ">= 4.11"

needed-pkgs:
    - name: "sglppow"
      version: "2.1"
      url: "https://gap-packages.github.io/sglppow/"

www: https://davidburrell.github.io/GRPS39/
readme: README.md
packageinfo: https://davidburrell.github.io/GRPS39/PackageInfo.g
github: https://github.com/davidburrell/GRPS39

downloads:
    - name: .tar.gz
      url: https://github.com/davidburrell/GRPS39/archive/refs/tags/v.0.1.tar.gz
    - name: .zip
      url: https://github.com/davidburrell/GRPS39/archive/refs/tags/v.0.1.zip

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Bur22</span>]   <b class='BibAuthor'>Burrell, D.</b>,
     <i class='BibTitle'>GRPS39, Library of the groups of order 19683,
             Version 0.1</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://davidburrell.github.io/GRPS39/">https://davidburrell.github.io/GRPS39/</a></span>.
    </p>
    

bibtex: |
    @misc{ GRPS390.1,
      author =           {Burrell, D.},
      title =            {{GRPS39}, Library of the groups of order 19683, {V}ersion 0.1},
      month =            {Jul},
      year =             {2022},
      note =             {GAP package},
      howpublished =     {\href    {https://davidburrell.github.io/GRPS39/}   {\texttt{https://davidburrell.github.io/}\discretionary
                          {}{}{}\texttt{GRPS39/}}},
      printedkey =       {Bur22}
    }

