name: GRPS39
version: "0.1"
license: "GPL-2.0-or-later"
date: 2022-07-31
description: |
     

authors:
    - name: Burrell David
      url: https://davidburrell.github.io/

maintainers:
    - name: Burrell David
      url: https://davidburrell.github.io/

GAP: ">= 4.11"

needed-pkgs:
    - name: "sglppow"
      version: "2.1"
      url: "https://gap-packages.github.io/sglppow/"

www: https://TODO/
readme: README.md
packageinfo: https://TODO/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://TODO//GRPS39-0.1.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Dav22</span>]   <b class='BibAuthor'>David, B.</b>,
     <i class='BibTitle'>GRPS39,  ,
             Version 0.1</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://TODO/">https://TODO/</a></span>.
    </p>
    

bibtex: |
    @misc{ GRPS390.1,
      author =           {David, B.},
      title =            {{GRPS39}, , {V}ersion 0.1},
      month =            {Jul},
      year =             {2022},
      note =             {GAP package},
      howpublished =     {\href {https://TODO/} {\texttt{https://TODO/}}},
      printedkey =       {Dav22}
    }

